### ISSUE TITLE
cryoDRGN_analyze_landscape_template should use updated mrc file handling

### ISSUE THREAD

**Issue by alkinkaz** [ml-struct-bio/cryodrgn#417] opened 2024-10-25 19:38 UTC
The `mrc.py` file has been superseded by `mrcfile.py` -- this should be reflected in the `cryoDRGN_analyze_landscape_template.ipynb` notebook. [Currently](https://github.com/ml-struct-bio/cryodrgn/blame/5bf68c5f4f4f886f1f47f5da7642d357bf013972/cryodrgn/templates/cryoDRGN_analyze_landscape_template.ipynb#L24), the first code cell in the notebook raises an `ImportError: cannot import name 'mrc' from 'cryodrgn'`.

**Comment by michal-g** [comment] 2024-10-25 20:27
This is a duplicate of #413, and you can find an explanation of what's going in that thread (this will be fixed in v3.4.2) — please remember to check existing issues before posting new ones!

**Closed** 2024-11-01 14:36 UTC
