### ISSUE TITLE
Utility to clear intermediate results

### ISSUE THREAD

**Issue by zhonge** [ml-struct-bio/cryodrgn#207] opened 2023-01-21 16:49 UTC
We should have a `cryodrgn_utils clean_workdir` tool that removes weights.*.pkl and z.*.pkl files of intermediate epochs from the workdir.

**Comment by michal-g** [comment] 2024-02-02 15:44
Removing this as a duplicate of #297!

**Closed by michal-g** 2024-02-02 15:44 UTC
Labels: enhancement
